# Generated by Django 5.0.1 on 2024-01-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favstocks',
            name='change',
        ),
        migrations.RemoveField(
            model_name='favstocks',
            name='changePer',
        ),
        migrations.RemoveField(
            model_name='favstocks',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='favstocks',
            name='price',
        ),
    ]
