# Generated by Django 5.0.1 on 2024-01-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0004_remove_favstocks_change_remove_favstocks_changeper_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavStocks',
        ),
    ]
