# Generated by Django 5.0.1 on 2024-01-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favstocks',
            name='changePer',
        ),
    ]
